<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>containerTableLeave</name>
   <tag></tag>
   <elementGuidId>85247b99-4189-4870-9d16-7c6df6039fd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7c7cf6d-a66f-4311-bd10-ce6ebafb5076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>d518c251-d8b3-47da-89e8-76e96cc8e1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DateEmployee NameLeave TypeLeave Balance (Days)Number of DaysStatusCommentsActions2023-12-06 to 2023-12-08Jimmy  CarterCAN - FMLA-2.002.00Taken (2.00)2023-12-01Jimmy  CarterCAN - Personal-1.001.00Taken (1.00)Request to approve </value>
      <webElementGuid>60ed4dd1-3b90-4969-abdc-08189c5fc906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>b3ff1e51-c50b-4250-b51e-208dfae4eadf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>bc69ea23-af7c-4103-8351-9f707bf99750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>d202bd6f-0e7f-46f2-9c2a-f70fccc51611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DateEmployee NameLeave TypeLeave Balance (Days)Number of DaysStatusCommentsActions2023-12-06 to 2023-12-08Jimmy  CarterCAN - FMLA-2.002.00Taken (2.00)2023-12-01Jimmy  CarterCAN - Personal-1.001.00Taken (1.00)Request to approve ' or . = 'DateEmployee NameLeave TypeLeave Balance (Days)Number of DaysStatusCommentsActions2023-12-06 to 2023-12-08Jimmy  CarterCAN - FMLA-2.002.00Taken (2.00)2023-12-01Jimmy  CarterCAN - Personal-1.001.00Taken (1.00)Request to approve ')]</value>
      <webElementGuid>3cd4782a-e783-4de7-bf07-669a7012fdb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
